var replacement_text = {
    "CarryMyLuggage": {
        "initCarryMyLuggage.exec": "Initializing carry my luggage",
        "NavigationMoveTowardsLocation_instructionPoint.exec": "Moving to instruction point",
        "DialogAskHuman_waveHand.exec": "Asking human to wave hand",
        "DialogSay_HelloIAmPepperYourButtler_animated.exec": "Introducing myself",
        "VisionFindHuman.exec": "Finding human",
        "VisionWaitForHumanWavingHand.exec": "Waiting for human to wave hand",
        "NavigationMoveTowardsObject_bag.exec": "Moving to bag",
        "DialogSay_CouldYouPleaseShowMeTheBagYouWantMeToCarry_animated.exec": "Asking human to show bag",
        "VisionFindObjectPointedByHuman.exec": "Finding bag",
        "DialogSay_CouldYouPleaseHangTheBagOnMyWrist_normal.exec": "Asking human to hang bag on wrist",
        "DialogSay_IAmReadyToFollowYouPleaseRaiseYourHandWhenYouReachedYourDestination_normal.exec": "Ready to follow human",
        "NavigationFollowHuman.exec": "Following human",
        "DialogSay_CouldYouPleaseTakeYourBag.exec": "Asking human to take bag",
        "NavigationMoveTowardsLocation_LivingRoom.exec": "Moving to living room",
        "NavigationMoveBehindHuman.exec": "Moving behind human",
        "DialogSay_CouldLastPersonInQueueWaveYourHand.exec": "Asking last person in queue to wave hand",
        "ManipulationBendArms_Right.exec": "Bending arms",
        "GestureLookAt_Human.exec": "Looking at human",
        "VisionWaitForHumanWavingHand.exec [HNotFound]": "Waiting for human to wave hand"
    },
    "GPSR": {
        "initGPSR.exec": "Initializing GPSR",
        "NavigationMoveTowardsLocation_arena.exec": "Moving to arena",
        "DialogAskHuman_waveHand.exec":"Asking human to wave hand",
        "DialogGreetHuman.exec":"Greeting human",
        "VisionFindHuman.exec":"Finding human",
        "VisionFindhumanWavingHand.exec": "Finding human waving hand",
        "NavigationMoveTowardsHuman.exec": "Moving towards human",
        "DialogAskHuman_Orders.exec": "Asking human for orders",
        "DialogListenOrders.exec": "Listening to orders",
        "ProcessOrders.exec": "Processing orders",
        "NavigationGoTo_arena.exec": "Going to arena",
        "NavigationMoveTowardsGPSRTarget.exec": "Moving towards GPSR target",
        "VisionWaitForDoorOpening.exec":"Waiting for door to open",
        "VisionFindObject_Cup.exec":"Finding cup",
        "NavigationMoveTowardsGPSRTarget_Cup.exec":"Moving towards GPSR target",
        "NavigationTurnTowards_Human.exec":"Turning towards human",
        "DialogAskHumanTake_Cup.exec":"Asking human to take cup",
        "DialogAskActionConfirmation.exec":"Asking human to confirm action",
        "DialogListenConfirmation.exec":"Listening to human's confirmation",
        "DialogAskHumanToFollow.exec": "Asking human to follow",
        "DialogTellHumanObjectLocation_Cup.exec": "Telling human object location",
        "OtherChangePlan_GPSRTakeOrder.exec": "Changing plan to take order",
        "OtherChangePlan_GPSRLobby.exec": "Changing plan to lobby",
        "OtherChangePlan_GPSRSubGiveMeCup.exec": "Changing plan to give me cup",
        "OtherChangePlan_GPSRSubShowMeCup.exec": "Changing plan to show me cup",
        "OtherChangePlan_GPSRSubMoveTowards.exec": "Changing plan to move towards",
        "OtherChangePlan_GPSRSubEscortHuman.exec": "Changing plan to escort human",
        "OtherChangePlan_GPSRSubFindObject.exec": "Changing plan to find object",
        "OtherChangePlan_GPSRSubFollowHuman.exec": "Changing plan to follow human",
        "OtherChangePlan_GPSRSubFindHuman.exec": "Changing plan to find human",
        "OtherChangePlan_GPSRSubTell.exec": "Changing plan to tell",
        "OtherChangePlan_GPSRSubTakeObject.exec:": "Changing plan to take object",
        "OtherChangePlan_GPSRSubGreet.exec": "Changing plan to greet",
        "VisionFindHumanAndStoreFeaturesWithDistanceFilter_2.exec": "Finding human and storing features with distance filter",
        "OtherIsHumanKnown_GPSR.exec": "Checking if human is known",
        "NavigationMoveTowardsHuman_GPSR.exec": "Moving towards human",
        "DialogAskHumanToFollowToLocation_GPSR.exec": "Asking human to follow to location",
        "DialogAskHumanNameConfirmation_GPSR.exec": "Asking human name confirmation",
        "NavigationMoveTowardsLocation_GPSR.exec": "Moving towards location",
        "DialogTellHumanDestinationArrived_GPSR_GPSR.exec": "Telling human destination arrived",
        "NavigationRotate_40.exec":"Rotating",
        "DialogListenConfirmation_GPSR.exec": "Listening to confirmation",
        "VisionFindObject_GPSR.exec": "Finding object",
        "DialogTellHumanObjectLocation_GPSR.exec": "Telling human object location",
        "NavigationFollowHuman.exec":"Following human",
        "DialogGreet_GPSR.exec": "Greeting",
        "DialogAskHumanToFollow_GPSR.exec": "Asking human to follow",
        "NavigationMoveTowardsLocation_Destination.exec": "Moving towards location",
        "DialogAskHumanTake_GPSR.exec": "Asking human to take",
        "NavigationMoveTowardsLocation_Source.exec": "Moving towards location",
        "OtherChooseTake.exec": "Choosing take",
        "DialogSay_IDontKnowTheLocationProvidedIWillSkipThisIntent.exec": "Saying I don't know the location provided",
        "NavigationMoveTowardsLocation_instructionPoint.exec":"Moving to instruction point",
        "VisionWaitForHumanWavingHand.exec":"Waiting for human to wave hand",
        "ManipulationLook_Up.exec":"Looking up",
        "ManipulationLook_Down.exec":"Looking down",
        "DialogSay_CanYouPleaseComeCloser.exec": "Asking human to come closer",
        "DialogSay_IHaveUnderstoodYourRequestButUnfortunatelyICanNotDoThatPleaseGiveMeAnotherOne.exec": "Saying I have understood your request but unfortunately I can not do that",
        "DialogSay_HaveICorrectlyUnderstoodYourRequestPleaseAnswerByYesOrNo.exec": "Asking if I have correctly understood the request"
    },
    "Receptionist": {
        "initReceptionist.exec": "Initializing receptionist",
        "NavigationMoveTowardsLocation_guestEntrance.exec": "Moving to guest entrance",
        "VisionFindHumanAndStoreFeatures.exec": "Finding guest",
        "DialogSay_WelcomeToTheTestArena.exec": "Welcoming guest",
        "DialogAskHuman_Name.exec": "Asking guest for name",
        "DialogListen_Name.exec": "Listening to guest's name",
        "DialogAskHuman_FavoriteDrink.exec;": "Asking guest for favorite drink",
        "DialogListen_Drink.exec": "Listening to guest's favorite drink",
        "DialogAskHumanToFollowToLocation_livingRoom.exec": "Asking guest to follow to living room",
        "NavigationMoveTowardsLocation_livingRoom.exec": "Moving to living room",
        "VisionFindEmptySeat.exec": "Finding empty seat",
        "DialogOfferSeatToHuman_Guest.exec": "Offering seat to guest",
        "DialogIntroduceAtoB_Guest1_Guest2.exec": "Introducing guest to other guest",
        "OtherCheckForMoreGuests.exec": "Checking for more guests",
        "DialogIntroduceAtoB_Guest2_Guest1.exec": "Introducing new guest to guests",
        "DialogIntroduceAtoB_Guest_Host.exec": "Introducing new guest to host",
        "DialogIntroduceAtoB_Host_Guest.exec": "Introducing host to new guest",
        "DialogSay_CouldYouStandInFrontOfMePlease.exec": "Asking guest to stand in front of me",
        "DialogSay_IWillBeLookingForAnEmptyChair.exec": "Looking for empty chair",
        "DialogSay_LetMeFindAnotherGuest.exec": "Looking for another guest",
        "NavigationRotate_40.exec": "Rotating",
        "ManipulationLook_Up.exec": "Looking up",
        "ManipulationLook_Down.exec": "Looking down",
        "VisionFindHumanAndStoreFeaturesWithDistanceFilter_host.exec": "Finding host",
        "NavigationRotate_minus40.exec": "Rotating"
    },
    "ServeBreakfast": {
        "initServeBreakfast.exec": "Initializing serve breakfast",
        "VisionWaitForDoorOpening.exec": "Waiting for door to open",
        "NavigationMoveTowardsLocation_kitchen.exec": "Moving to kitchen",
        "NavigationMoveTowardsLocation_kitchenShelf.exec": "Moving to kitchen shelf",
        "VisionFindObject_Bowl.exec": "Finding bowl",
        "ManipulationGraspObject_Bowl_Both.exec": "Grasping bowl",
        "NavigationMoveTowardsLocation_KitchenTable.exec": "Moving to kitchen table",
        "ManipulationPutObject_Both.exec": "Putting bowl on table",
        "VisionFindObject_Spoon.exec": "Finding spoon",
        "ManipulationGraspObject_Spoon.exec": "Grasping spoon",
        "ManipulationPutObject_Left.exec": "Putting spoon on left side of table",
        "VisionFindObject_CerealBox.exec": "Finding cereal box",
        "ManipulationGraspObject_CerealBox_Both.exec": "Grasping cereal box",
        "VisionFindObject_MilkCarton.exec": "Finding milk carton",
        "ManipulationGraspObject_MilkCarton_Both.exec": "Grasping milk carton",
        "ManipulationPourObject_Both_Bowl.exec": "Pouring milk into bowl"
    },
    "StoringGroceries": {
        "initStoringGroceries.exec": "Initializing storing groceries",
        "NavigationMoveTowardsLocation_livingRoom.exec":"Moving to living room",
        "VisionWaitForDoorOpening.exec":"Waiting for door to open",
        "DialogSay_LetsSeeWhatWeCanFindHere.exec": "Looking for groceries",
        "NavigationMoveTowardsLocation_sideTable.exec": "Moving to side table",
        "VisionFindObject_All.exec": "Locating grocery items",
        "DialogAskHumanTakeLastObject.exec" : "Asking human to take last object",
        "DialogAskActionConfirmation.exec": "Asking human to confirm action",
        "DialogListenConfirmation.exec": "Listening to human's confirmation",
        "NavigationMoveTowardsLocation_cupboard.exec": "Moving to cupboard",
        "VisionLocatePositionToPlaceObject.exec": "Locating position to place object",
        "OtherCheckMoreObjectToFind.exec": "Checking for more objects to find",
        "ManipulationLook_Down.exec":"Looking down",
        "ManipulationLook_Up.exec":"Looking up",
        "DialogSay_IAmDoneWithMyWorkHere.exec": "Done with work",
        "DialogSay_NowPleaseFollowMe.exec": "Asking human to follow me",
        "DialogSay_LetMeThinkAboutWhereTheObjectNeedsToBePlaced.exec": "Thinking about where to place object",
        "DialogSay_PleaseFollowMeToOurStartingPoint.exec": "Asking human to follow me to starting point"
    },
    "CleanTheTable": {
        "initCleanTheTable.exec": "Initializing clean the table",
        "VisionWaitForDoorOpening.exec":"Waiting for door to open",
        "NavigationMoveTowardsLocation_kitchen.exec":"Moving to kitchen",
        "VisionFindObject_Table.exec": "Finding table",
        "NavigationRotate_minus40.exec": "Rotating",
        "VisionFindObject_Dishwasher.exec": "Finding dishwasher",
        "ManipulationLook_Down.exec":"Looking down",
        "ManipulationLook_Up.exec":"Looking up",
        "NavigationMoveTowardsObject_Dishwasher.exec": "Moving to dishwasher",
        "VisionFindObject_DishwasherHandle.exec": "Finding dishwasher handle",
        "ManipulationGrabHandle_DishwasherHandle_Right.exec": "Grabbing dishwasher handle",
        "VisionFindObject_DishwasherRack.exec": "Finding dishwasher rack",
        "ManipulationPullObject_DishwasherRack_Both.exec": "Pulling dishwasher rack",
        "NavigationMoveTowardsObject_Table.exec": "Moving to table"
    },
    "Restaurant": {
        "initRestaurant.exec": "Initializing restaurant",
        "DialogAskHuman_waveHand.exec":"Asking human to wave hand",
        "VisionWaitForHumanWavingHand_storeInformation.exec": "Waiting for human to wave hand",
        "NavigationMoveTowardsHuman_nextCustomer.exec": "Moving to next customer",
        "GestureLookAt_nextCustomer.exec": "Looking at next customer",
        "DialogSay_Hello.exec": "Saying hello",
        "DialogSay_WhatDrinkWouldYouLikeToday.exec": "Asking for drink",
        "DialogListen_Drink.exec":"Listening to guest's favorite drink order",
        "NavigationMoveTowardsLocation_kitchenTable.exec": "Moving to kitchen table",
        "DialogAskOperatorHelp_CustomerOrder.exec": "Asking operator to help with customer's order",
        "DialogAskActionConfirmation.exec":"Asking human to confirm action",
        "DialogListenConfirmation.exec":"Listening to human's confirmation",
        "DialogAskHuman_TakeOrderOnTray.exec":"Asking human to take order on tray"

    },
    "Stickler": {
        "initStickler.exec": "Initializing stickler",
        "NavigationMoveTowardsLocation_centerPoint.exec": "Moving to center point",
        "DialogSay_IWillSeeIfThereIsAnySticklerInTheHouse.exec": "Looking for stickler",
        "OtherChangePlan_SticklerLobby.exec": "Changing plan to stickler lobby",
        "ManipulationLook_Up.exec":"Looking up",
        "DialogSay_YouAreBreakingTheForbiddenRoomRule.exec": "Telling human they are breaking the rule",
        "ManipulationPointAt.exec": "Pointing at human",
        "DialogSay_NoGuestIsAllowedInsideThisRoomCouldYouPleaseLeaveThisRoom.exec": "Asking human to leave the room",
        "OtherChangePlan_SticklerForbiddenRoomSecondAttempt.exec": "Changing plan to stickler forbidden room second attempt",
        "OtherWait_5.exec": "Waiting",
        "DialogSay_IFoundAPersonInTheForbiddenRoom.exec": "Telling human I found a person in the forbidden room",
        "DialogSay_IWillNevigateTowardsForbiddenRoom.exec": "Telling human I will navigate towards the forbidden room",
        "NavigationMoveTowardsLocation_sticklerBedroom1.exec": "Moving to stickler bedroom",
        "DialogSay_ThankYouForRespectingTheRule.exec": "Thanking human for respecting the rule",
        "DialogSay_YouAreStillBreakingTheForbiddenRoomRule.exec": "Telling human they are still breaking the rule",
        "DialogSay_IKindlyRequestYouAgainToLeaveTheRoom.exec": "Asking human to leave the room",
        "ManipulationLook_DownStickler.exec": "Looking down",
        "NavigationMoveTowardsLocation_startingPointStickler.exec": "Moving to starting point",
        "NavigationMoveTowardsLocation_sticklerBedroom2.exec": "Moving to stickler bedroom",
        "VisionFindHumanAndStoreFeaturesWithDistanceFilter_3.exec": "Finding human",
        "VisionFindStickler.exec": "Finding stickler",
        "DialogSay_IKindlyRequestYouAgainToComeOutOfTheRoom.exec": "Asking human to come out of the room",
        "OtherFindHumanInForbiddenRoom.exec": "Finding human in forbidden room",
        "NavigationRotate_minus40.exec": "Rotating",
        "OtherChangePlan_SticklerShoesFirstAttempt.exec": "Changing plan to stickler shoes first attempt",
        "OtherChangePlan_SticklerNoDrinkFirstAttempt.exec": "First time asking human to bring drink",
        "OtherChangePlan_SticklerLitterFirstAttempt.exec": "First time asking human not to litter",
        "OtherChangePlan_SticklerForbiddenRoomFirstAttempt.exec": "First time asking human not to enter forbidden room",
        "DialogSay_YouAreBreakingTheCompulsoryHydrationRule.exec": "Telling human they are breaking the compulsory hydration rule",
        "DialogSay_CouldYouPleaseFindADrinkAndReturnToYourPosition.exec": "Asking human to find a drink and return to their position",
        "OtherChangePlan_StricklerNoDrinkSecondAttempt.exec": "Second time asking human to bring drink",
        "DialogSay_YouHaveNoDrinkInYourHand.exec": "Telling human they have no drink in their hand",
        "DialogSay_IKindlyRemindYouThatYouAreBreakingTheCompulsoryHydrationRule.exec": "Reminding human they are breaking the compulsory hydration rule",
        "VisionFindHumanWithTimeout_10.exec": "Finding human",
        "DialogSay_IKindlyRequestYouAgainToBringYourDrinkToStayHydrated.exec": "Asking human to bring their drink to stay hydrated",
        "VisionFindPersonWithoutDrink.exec": "Finding person without drink",
        "initFindMyMate.exec": "Initializing find my mate",
        "VisionFindPersonWithShoes_2.exec": "Finding person with shoes",
        "DialogSay_YouAreWearingShoes.exec": "Telling human they are wearing shoes",
        "DialogSay_IWillSeeIfThereIsAnySticklerInTheRoom.exec" : "Looking for stickler",
        "ManipulationLook_Down.exec":"Looking down",
        "NavigationRotate_40.exec": "Rotating",
        "VisionFindHuman.exec": "Finding human",
        "DialogSay_YouDidNotRemoveYourShoes.exec": "Telling human they did not remove their shoes",
        "DialogSay_IKindlyRequestYouAgainToRemoveYourShoes.exec": "Asking human to remove their shoes",
        "DialogSay_CouldYouPleaseRemoveYourShoesOutsideAndReturnToYourPosition.exec": "Asking human to remove their shoes outside and return to their position",
        "OtherChangePlan_StricklerShoesSecondAttempt.exec": "Second time asking human to remove shoes",
        "OtherWait_10.exec": "Waiting",
        "DialogSay_NoShoesAreAllowedInsideTheHouse.exec": "Telling human no shoes are allowed inside the house",
        "VisionFindPersonWithShoes.exec": "Finding person with shoes"
    }
}

export { replacement_text };
